story.heroDefense;
story.defenseBonus = 0;
story.initialheroHP;
story.heroHP;
story.enemyname;
story.enemystrength;
story.enemyagility;
story.enemyintelligence;
story.enemyresolve;
story.enemyspecial
story.initialenemyHP;
story.enemyHP;
story.enemyDefense;
story.enemyDefenseBonus = 0;
story.hitdamage = 0;
story.combatdistance;
story.specialuse =0;
story.companionactionuseR =0;
story.companionactionuseA =0;
story.companionactionuseM =0;
story.companionactionuseW =0;
story.companionactionuseB =0;
story.companionactionuseE =0;
story.companionactionuseT =0;
story.companionactionuseS =0;
story.turnaction =0;
story.optioncounter;
story.lastroll = 0;
var effects = {burn: 0, poison: 0, wrestle: 0, thorns: 0, bloody: 0, fallen: 0, caltrops: 0, nightmare: 0, robot: 0};
var enemyeffects = {burn: 0, poison: 0, wrestle: 0, thorns: 0, bloody: 0, fallen: 0, caltrops: 0, nightmare: 0, robot: 0};